tasks:
  - name: Upgrade pip and outdated packages 
    init: |
      python -m pip install --upgrade pip
      pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U 
      python -m pip install Django
    command: |
      python manage.py migrate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
